language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
- export TZ='Asia/Shanghai'  
- npm install -g hexo

before_script:
- git config --global user.name 'bullettrain1433'
- git config --global user.email 'bullettrain1433@gmail.com'

install:
- npm install

script:
- hexo clean
- hexo generate

after_script:
  - sed -i "s/gh_token/${githubblog}/g" ./_config.yml
  # token_name 为上一步中Travis环境变量中设置的name
  - hexo deploy

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/BulletTrain/Bullettrain.github.io.git
   - secure: f20njxkDpxiqiXqEM8egGSWF2ATksRqj8ezmG+cjNoRoKSJ6GpTqzqU5mQI+yPKDOrx2/CGp5YBC0QuiCg8mbbZPDDJgMbT1LoOlcVChqVswgAQHWC1fCg95KYTgr98Gbpi8jDx6goECqTS2mSPrGZ2ANcg4TFjUzCDOxEBX0TYEcrI7ulHDRrEPwCWXzqh6PP0ofGGiKmYSfbOxY3/pN795eAqYKbl4p1JhoYiBDiJKNPZAOaihAE091Qd7UISPhzH8oQSKtQja7rbjDTNb1BaQvbk0fAzPFJcdpRRWo4uPiHd0v6Ets5vQJAvKIM45C6p05+Jr6qsYCcCX5anxqVj8++BkbKY+Vp3FLGIVfOSj/2c3tUFNxzDd1nbQjmZo6Rz7CtPpjaAq+tDhpAKQR62M2mRWF0RYkJrfnzHoEMWCjwGtZitk2JGJX3uJ0/QgnYVDuqQEyKVtQNqzXOYCg9ik2YZ/iYivniGjNCiIHbSxpi/ZX9L56X/4UolznXvM+LHThfizSAVOBSERW8Av+CFQuHaDQapoIO4XhESR8EHwQBNvJKaecpKmHwI4Hq4dFNrPdOW6QQ+uOMzxmYH8qmXB0kXMNjAZeVxl1xqLvdbH3Zu/pUgizIaVxoQo4FHkykMnULGE+HwBirCJNB5uTzKe5GJd0CSJDy1dRziUAqI=
