language: node_js
node_js: stable

before_install:
- export TZ='Asia/Shanghai'  
- npm install -g hexo
#- npm install -- save-dev hexo-util
#- npm install -- save-dev hexo-fs
#- npm install -- save-dev hexo-deployer-git
before_script:
- git config --global user.name 'bullettrain1433'
- git config --global user.email 'bullettrain1433@gmail.com'
- sed -i'' "s~git@github.com:BulletTrain/Bullettrain.github.io.git~https://${githubblog}:x-oauth-basic@github.com/BulletTrain/Bullettrain.github.io.git~" _config.yml
# S: Build Lifecycle
install:
- npm install
script:
- hexo clean
- hexo generate
- hexo deploy
#after_success:
#- hexo deploy

#before_script:
 # - npm install -g gulp

after_script:
  - cd ./public
  - git init
  - git config user.name "bullettrain1433"
  - git config user.email "bullettrain1433@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${githubblog}@${GH_REF}" master:master

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/BulletTrain/Bullettrain.github.io.git
   - secure: f20njxkDpxiqiXqEM8egGSWF2ATksRqj8ezmG+cjNoRoKSJ6GpTqzqU5mQI+yPKDOrx2/CGp5YBC0QuiCg8mbbZPDDJgMbT1LoOlcVChqVswgAQHWC1fCg95KYTgr98Gbpi8jDx6goECqTS2mSPrGZ2ANcg4TFjUzCDOxEBX0TYEcrI7ulHDRrEPwCWXzqh6PP0ofGGiKmYSfbOxY3/pN795eAqYKbl4p1JhoYiBDiJKNPZAOaihAE091Qd7UISPhzH8oQSKtQja7rbjDTNb1BaQvbk0fAzPFJcdpRRWo4uPiHd0v6Ets5vQJAvKIM45C6p05+Jr6qsYCcCX5anxqVj8++BkbKY+Vp3FLGIVfOSj/2c3tUFNxzDd1nbQjmZo6Rz7CtPpjaAq+tDhpAKQR62M2mRWF0RYkJrfnzHoEMWCjwGtZitk2JGJX3uJ0/QgnYVDuqQEyKVtQNqzXOYCg9ik2YZ/iYivniGjNCiIHbSxpi/ZX9L56X/4UolznXvM+LHThfizSAVOBSERW8Av+CFQuHaDQapoIO4XhESR8EHwQBNvJKaecpKmHwI4Hq4dFNrPdOW6QQ+uOMzxmYH8qmXB0kXMNjAZeVxl1xqLvdbH3Zu/pUgizIaVxoQo4FHkykMnULGE+HwBirCJNB5uTzKe5GJd0CSJDy1dRziUAqI=
